spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/jsboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password:
#  cache:
#    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.91.128/
flyway:
    baselineOnMigrate = true
 # redis 配置
redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌秘钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    expireTime: 30

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

