spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/jsboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password:
#  cache:
#    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.91.128/
flyway:
    baselineOnMigrate = true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

